server:
  port: 8080
spring:
  datasource:
#    url: jdbc:sqlserver://localhost:1433;DatabaseName=SBO-COMMON
#    username: sa
#    password:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://124.193.172.26:1433;DatabaseName=SBO_AKYC_PORT_TEST
    username: sa
    password: ak2003.com.cn
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
logging:
  config: classpath:logback-spring.xml